package lee.code.mb.lists;

import lee.code.core.util.bukkit.BukkitUtils;
import lee.code.mb.GoldmanMysteryBox;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.persistence.PersistentDataType;

@AllArgsConstructor
public enum Loot {
    //pets
    BROWN_AND_WHITE_COW_PET(new String[] { "addperm %player% pets.use.cow", "addperm %player% pets.use.brown_and_white_cow" }, Material.PLAYER_HEAD, "&e&lBrown And White Cow Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2RmYTBhYzM3YmFiYTJhYTI5MGU0ZmFlZTQxOWE2MTNjZDYxMTdmYTU2OGU3MDlkOTAzNzQ3NTNjMDMyZGNiMCJ9fX0=", 0),
    RED_MOOSHROOM_COW_PET(new String[] { "addperm %player% pets.use.cow", "addperm %player% pets.use.red_mooshroom_cow" }, Material.PLAYER_HEAD, "&e&lRed Mooshroom Cow Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmI1Mjg0MWYyZmQ1ODllMGJjODRjYmFiZjllMWMyN2NiNzBjYWM5OGY4ZDZiM2RkMDY1ZTU1YTRkY2I3MGQ3NyJ9fX0=", 0),
    BROWN_MOOSHROOM_COW_PET(new String[] { "addperm %player% pets.use.cow", "addperm %player% pets.use.brown_mooshroom_cow" }, Material.PLAYER_HEAD, "&e&lBrown Mooshroom Cow Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjZkNWZjNzAzMWFjYzk1YmVlYjUyODc1ZjE1NDA4ZTk3OWEwYTljMzkxYjZkYjdlY2VlN2U0MDAwNzJkZTVjNCJ9fX0", 0),
    CHICKEN_PET(new String[] { "addperm %player% pets.use.chicken" }, Material.PLAYER_HEAD, "&e&lChicken Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2YzN2Q1MjRjM2VlZDE3MWNlMTQ5ODg3ZWExZGVlNGVkMzk5OTA0NzI3ZDUyMTg2NTY4OGVjZTNiYWM3NWUifX19", 0),
    PIG_PET(new String[] { "addperm %player% pets.use.pig" }, Material.PLAYER_HEAD, "&e&lPig Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjIxNjY4ZWY3Y2I3OWRkOWMyMmNlM2QxZjNmNGNiNmUyNTU5ODkzYjZkZjRhNDY5NTE0ZTY2N2MxNmFhNCJ9fX0=", 0),
    RED_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.red_cat" }, Material.PLAYER_HEAD, "&e&lRed Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGI0MzJiN2M4NDY4Y2Y2ODkyODY4ZDg2M2QzOGRkOWU2YjRjYzA1NTU3NjhiOGUwNzEzN2Y4NzhmMzNlNWIifX19", 0),
    BLACK_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.black_cat" }, Material.PLAYER_HEAD, "&e&lBlack Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGZkMTBjOGU3NWY2NzM5OGM0NzU4N2QyNWZjMTQ2ZjMxMWMwNTNjYzVkMGFlYWI4NzkwYmNlMzZlZTg4ZjVmOCJ9fX0=", 0),
    SIAMESE_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.siamese_cat" }, Material.PLAYER_HEAD, "&e&lSiamese Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDViM2Y4Y2E0YjNhNTU1Y2NiM2QxOTQ0NDk4MDhiNGM5ZDc4MzMyNzE5NzgwMGQ0ZDY1OTc0Y2M2ODVhZjJlYSJ9fX0=", 0),
    BRITISH_SHORTHAIR_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.british_shorthair_cat" }, Material.PLAYER_HEAD, "&e&lBritish Shorthair Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTM4OWUwZDVkM2U4MWY4NGI1NzBlMjk3ODI0NGIzYTczZTVhMjJiY2RiNjg3NGI0NGVmNWQwZjY2Y2EyNGVlYyJ9fX0=", 0),
    CALICO_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.calico_cat" }, Material.PLAYER_HEAD, "&e&lCalico Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzQwMDk3MjcxYmI2ODBmZTk4MWU4NTllOGJhOTNmZWEyOGI4MTNiMTA0MmJkMjc3ZWEzMzI5YmVjNDkzZWVmMyJ9fX0=", 0),
    PERSIAN_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.persian_cat" }, Material.PLAYER_HEAD, "&e&lPersian Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmY0MGM3NDYyNjBlZjkxYzk2YjI3MTU5Nzk1ZTg3MTkxYWU3Y2UzZDVmNzY3YmY4Yzc0ZmFhZDk2ODlhZjI1ZCJ9fX0=", 0),
    RAGDOLL_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.ragdoll_cat" }, Material.PLAYER_HEAD, "&e&lRagdoll Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGM3YTQ1ZDI1ODg5ZTNmZGY3Nzk3Y2IyNThlMjZkNGU5NGY1YmMxM2VlZjAwNzk1ZGFmZWYyZTgzZTBhYjUxMSJ9fX0=", 0),
    WHITE_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.white_cat" }, Material.PLAYER_HEAD, "&e&lWhite Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjFkMTVhYzk1NThlOThiODlhY2E4OWQzODE5NTAzZjFjNTI1NmMyMTk3ZGQzYzM0ZGY1YWFjNGQ3MmU3ZmJlZCJ9fX0=", 0),
    JELLIE_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.jellie_cat" }, Material.PLAYER_HEAD, "&e&lJellie Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTBkYjQxMzc2Y2E1N2RmMTBmY2IxNTM5ZTg2NjU0ZWVjZmQzNmQzZmU3NWU4MTc2ODg1ZTkzMTg1ZGYyODBhNSJ9fX0=", 0),
    ALL_BLACK_CAT_PET(new String[] { "addperm %player% pets.use.cat", "addperm %player% pets.use.all_black_cat" }, Material.PLAYER_HEAD, "&e&lAll Black Cat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjJjMWU4MWZmMDNlODJhM2U3MWUwY2Q1ZmJlYzYwN2UxMTM2MTA4OWFhNDdmMjkwZDQ2YzhhMmMwNzQ2MGQ5MiJ9fX0=", 0),
    OCELOT_PET(new String[] { "addperm %player% pets.use.ocelot" }, Material.PLAYER_HEAD, "&e&lOcelot Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTFmMDdlM2YyZTVmMjU2YmZhZGU2NjZhOGRlMWI1ZDMwMjUyYzk1ZTk4ZjhhOGVjYzZlM2M3YjdmNjcwOTUifX19", 0),
    WOLF_PET(new String[] { "addperm %player% pets.use.wolf" }, Material.PLAYER_HEAD, "&e&lWolf Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjlkMWQzMTEzZWM0M2FjMjk2MWRkNTlmMjgxNzVmYjQ3MTg4NzNjNmM0NDhkZmNhODcyMjMxN2Q2NyJ9fX0=", 0),
    RED_PARROT_PET(new String[] { "addperm %player% pets.use.parrot", "addperm %player% pets.use.red_parrot" }, Material.PLAYER_HEAD, "&e&lRed Parrot Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTRiYThkNjZmZWNiMTk5MmU5NGI4Njg3ZDZhYjRhNTMyMGFiNzU5NGFjMTk0YTI2MTVlZDRkZjgxOGVkYmMzIn19fQ==", 0),
    BLUE_PARROT_PET(new String[] { "addperm %player% pets.use.parrot", "addperm %player% pets.use.blue_parrot" }, Material.PLAYER_HEAD, "&e&lBlue Parrot Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWNhNTgwYjA1MWM2M2JlMjlkYTU0NWE5YWE3ZmY3ZTEzNmRmNzdhODFjNjdkYzFlZTllNjE3MGMxNGZiMzEwIn19fQ==", 0),
    GREEN_PARROT_PET(new String[] { "addperm %player% pets.use.parrot", "addperm %player% pets.use.green_parrot" }, Material.PLAYER_HEAD, "&e&lGreen Parrot Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWI5YTM2YzU1ODlmM2EyZTU5YzFjYWE5YjNiODhmYWRhNzY3MzJiZGI0YTc5MjYzODhhOGMwODhiYmJjYiJ9fX0=", 0),
    CYAN_PARROT_PET(new String[] { "addperm %player% pets.use.parrot", "addperm %player% pets.use.cyan_parrot" }, Material.PLAYER_HEAD, "&e&lCyan Parrot Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmI5NGYyMzZjNGE2NDJlYjJiY2RjMzU4OWI5YzNjNGEwYjViZDVkZjljZDVkNjhmMzdmOGM4M2Y4ZTNmMSJ9fX0=", 0),
    GRAY_PARROT_PET(new String[] { "addperm %player% pets.use.parrot", "addperm %player% pets.use.gray_parrot" }, Material.PLAYER_HEAD, "&e&lGray Parrot Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Q2ZjRhMjFlMGQ2MmFmODI0Zjg3MDhhYzYzNDEwZjFhMDFiYmI0MWQ3ZjRhNzAyZDk0NjljNjExMzIyMiJ9fX0=", 0),
    TURTLE_PET(new String[] { "addperm %player% pets.use.turtle" }, Material.PLAYER_HEAD, "&e&lTurtle Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMGE0MDUwZTdhYWNjNDUzOTIwMjY1OGZkYzMzOWRkMTgyZDdlMzIyZjlmYmNjNGQ1Zjk5YjU3MThhIn19fQ==", 0),
    WHITE_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.white_sheep" }, Material.PLAYER_HEAD, "&e&lWhite Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjMxZjljY2M2YjNlMzJlY2YxM2I4YTExYWMyOWNkMzNkMThjOTVmYzczZGI4YTY2YzVkNjU3Y2NiOGJlNzAifX19", 0),
    PINK_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.pink_sheep" }, Material.PLAYER_HEAD, "&e&lPink Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmFjNzRhMmI5YjkxNDUyZTU2ZmExZGRhNWRiODEwNzc4NTZlNDlmMjdjNmUyZGUxZTg0MWU1Yzk1YTZmYzVhYiJ9fX0=", 0),
    GREEN_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.green_sheep" }, Material.PLAYER_HEAD, "&e&lGreen Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTAxNzIxNWM3ZjhkYjgyMDQwYWEyYzQ3Mjk4YjY2NTQxYzJlYjVmN2Y5MzA0MGE1ZDIzZDg4ZjA2ODdkNGIzNCJ9fX0=", 0),
    LIME_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.lime_sheep" }, Material.PLAYER_HEAD, "&e&lLime Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTJhMjQ0OGY1OGE0OTEzMzI0MzRlODVjNDVkNzg2ZDg3NDM5N2U4MzBhM2E3ODk0ZTZkOTI2OTljNDJiMzAifX19", 0),
    ORANGE_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.orange_sheep" }, Material.PLAYER_HEAD, "&e&lOrange Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjA5ODM5N2EyNzBiNGMzZDJiMWU1NzRiOGNmZDNjYzRlYTM0MDkwNjZjZWZlMzFlYTk5MzYzM2M5ZDU3NiJ9fX0=", 0),
    MAGENTA_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.magenta_sheep" }, Material.PLAYER_HEAD, "&e&lMagenta Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTgzNjU2NWM3ODk3ZDQ5YTcxYmMxODk4NmQxZWE2NTYxMzIxYTBiYmY3MTFkNDFhNTZjZTNiYjJjMjE3ZTdhIn19fQ==", 0),
    LIGHT_BLUE_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.light_blue_sheep" }, Material.PLAYER_HEAD, "&e&lLight Blue Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWE2MjRmNTk2NmJlZGQ2ZTY3ZjY1NGI1OWU5MjQ5YjJlY2YzMDdkOTAzMzM5YmMxOTk5MjM5NzdmNGM4YyJ9fX0=", 0),
    YELLOW_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.yellow_sheep" }, Material.PLAYER_HEAD, "&e&lYellow Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjZhNDExMmRmMWU0YmNlMmE1ZTI4NDE3ZjNhYWZmNzljZDY2ZTg4NWMzNzI0NTU0MTAyY2VmOGViOCJ9fX0=", 0),
    PURPLE_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.purple_sheep" }, Material.PLAYER_HEAD, "&e&lPurple Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWU1Mjg2N2FmZWYzOGJiMTRhMjZkMTQyNmM4YzBmMTE2YWQzNDc2MWFjZDkyZTdhYWUyYzgxOWEwZDU1Yjg1In19fQ==", 0),
    BLUE_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.blue_sheep" }, Material.PLAYER_HEAD, "&e&lBlue Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDllYzIyODE4ZDFmYmZjODE2N2ZiZTM2NzI4YjI4MjQwZTM0ZTE2NDY5YTI5MjlkMDNmZGY1MTFiZjJjYTEifX19", 0),
    CYAN_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.cyan_sheep" }, Material.PLAYER_HEAD, "&e&lCyan Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZmNmM3ZTdmZDUxNGNlMGFjYzY4NTkzMjI5ZTQwZmNjNDM1MmI4NDE2NDZlNGYwZWJjY2NiMGNlMjNkMTYifX19", 0),
    BROWN_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.brown_sheep" }, Material.PLAYER_HEAD, "&e&lBrown Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTU1YWQ2ZTVkYjU2OTJkODdmNTE1MTFmNGUwOWIzOWZmOWNjYjNkZTdiNDgxOWE3Mzc4ZmNlODU1M2I4In19fQ==", 0),
    BLACK_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.black_sheep" }, Material.PLAYER_HEAD, "&e&lBlack Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzI2NTIwODNmMjhlZDFiNjFmOWI5NjVkZjFhYmYwMTBmMjM0NjgxYzIxNDM1OTUxYzY3ZDg4MzY0NzQ5ODIyIn19fQ==", 0),
    RED_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.red_sheep" }, Material.PLAYER_HEAD, "&e&lRed Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODM5YWY0NzdlYjYyNzgxNWY3MjNhNTY2MjU1NmVjOWRmY2JhYjVkNDk0ZDMzOGJkMjE0MjMyZjIzZTQ0NiJ9fX0=", 0),
    GRAY_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.gray_sheep" }, Material.PLAYER_HEAD, "&e&lGray Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDI4N2ViNTAxMzkxZjI3NTM4OWYxNjZlYzlmZWJlYTc1ZWM0YWU5NTFiODhiMzhjYWU4N2RmN2UyNGY0YyJ9fX0=", 0),
    LIGHT_GRAY_SHEEP_PET(new String[] { "addperm %player% pets.use.sheep", "addperm %player% pets.use.light_gray_sheep" }, Material.PLAYER_HEAD, "&e&lLight Gray Sheep Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2UxYWM2ODM5OTNiZTM1NTEyZTFiZTMxZDFmNGY5OGU1ODNlZGIxNjU4YTllMjExOTJjOWIyM2I1Y2NjZGMzIn19fQ==", 0),
    BROWN_LLAMA_PET(new String[] { "addperm %player% pets.use.llama", "addperm %player% pets.use.brown_llama" }, Material.PLAYER_HEAD, "&e&lBrown Llama Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzc3NmE3OGY5NjI0NGUzZGE3MzJmYWZmZDkzYTMzOTgzNGRiMjdiNjk1NWJmN2E5YjI0YWU5ODEyNWI3ZWQifX19", 0),
    CREAMY_LLAMA_PET(new String[] { "addperm %player% pets.use.llama", "addperm %player% pets.use.creamy_llama" }, Material.PLAYER_HEAD, "&e&lCreamy Llama Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmE1ZjEwZTZlNjIzMmYxODJmZTk2NmY1MDFmMWMzNzk5ZDQ1YWUxOTAzMWExZTQ5NDFiNWRlZTBmZWZmMDU5YiJ9fX0=", 0),
    GRAY_LLAMA_PET(new String[] { "addperm %player% pets.use.llama", "addperm %player% pets.use.gray_llama" }, Material.PLAYER_HEAD, "&e&lGray Llama Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2YyNGU1NmZkOWZmZDcxMzNkYTZkMWYzZTJmNDU1OTUyYjFkYTQ2MjY4NmY3NTNjNTk3ZWU4MjI5OWEifX19", 0),
    WHITE_LLAMA_PET(new String[] { "addperm %player% pets.use.llama", "addperm %player% pets.use.white_llama" }, Material.PLAYER_HEAD, "&e&lWhite Llama Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODNkOWI1OTE1OTEyZmZjMmI4NTc2MWQ2YWRjYjQyOGE4MTJmOWI4M2ZmNjM0ZTMzMTE2MmNlNDZjOTllOSJ9fX0=", 0),
    POLAR_BEAR_PET(new String[] { "addperm %player% pets.use.polar_bear" }, Material.PLAYER_HEAD, "&e&lPolar Bear Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDQ2ZDIzZjA0ODQ2MzY5ZmEyYTM3MDJjMTBmNzU5MTAxYWY3YmZlODQxOTk2NjQyOTUzM2NkODFhMTFkMmIifX19", 0),
    PLAINS_VILLAGER_PET(new String[] { "addperm %player% pets.use.villager", "addperm %player% pets.use.plains_villager" }, Material.PLAYER_HEAD, "&e&lPlains Villager Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDFiODMwZWI0MDgyYWNlYzgzNmJjODM1ZTQwYTExMjgyYmI1MTE5MzMxNWY5MTE4NDMzN2U4ZDM1NTU1ODMifX19", 0),
    DESERT_VILLAGER_PET(new String[] { "addperm %player% pets.use.villager", "addperm %player% pets.use.desert_villager" }, Material.PLAYER_HEAD, "&e&lDesert Villager Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTBiZjZkZjM3ZGFjNmNhNjA4OWQyYmEwNDEzNWYyMjNkNGQ4NTBkZjlmMDljN2VjNGVhZjhjNTA3NjRjYmM1MCJ9fX0=", 0),
    JUNGLE_VILLAGER_PET(new String[] { "addperm %player% pets.use.villager", "addperm %player% pets.use.jungle_villager" }, Material.PLAYER_HEAD, "&e&lJungle Villager Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDRiMDYyYTlmODM5OWRjY2I2MjUxYTc0ZTYxODY0NzM0MmEzYzAyNDBjYTU2ZjM0NjE0ZDUyZjYwYTNmZWNlYyJ9fX0=", 0),
    SAVANNA_VILLAGER_PET(new String[] { "addperm %player% pets.use.villager", "addperm %player% pets.use.savanna_villager" }, Material.PLAYER_HEAD, "&e&lSavanna Villager Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGQ5ZWU1ZDhiNThmZGRkMjdiYzY3OWMwNTQ4ZjU1YmFhODQ1ZjlmMWRmNWU4OGM3YzViZGE2ZWI5ZGYyYjM5OSJ9fX0=", 0),
    SNOW_VILLAGER_PET(new String[] { "addperm %player% pets.use.villager", "addperm %player% pets.use.snow_villager" }, Material.PLAYER_HEAD, "&e&lSnow Villager Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDFmMTFmMzlmZTQ1MjcxZTNhNWM2MDM4ODJiYjI1ZjNkNjAxYWQ0ZjY4OTljMDkyMGZlNzkxMjgzYjBiZjFlNCJ9fX0=", 0),
    SWAMP_VILLAGER_PET(new String[] { "addperm %player% pets.use.villager", "addperm %player% pets.use.swamp_villager" }, Material.PLAYER_HEAD, "&e&lSwamp Villager Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWFkN2E5ZThmZTJiZGZlYTAzYmIxZjlmYWJlNDVmYjEwY2Y2OWE3MmUzNzYwZTVmZDlhNzBmMzM4NGM1MzZhZCJ9fX0=", 0),
    TAIGA_VILLAGER_PET(new String[] { "addperm %player% pets.use.villager", "addperm %player% pets.use.taiga_villager" }, Material.PLAYER_HEAD, "&e&lTaiga Villager Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjFlODk3NzE5YjU0Yjg0NGZhMDU5ZjA0ODE3ZTEzZGI4YWJkOTdlNmJkYjA2MjQwOTMwMzJiNDUxMmY3YTFjNiJ9fX0=", 0),
    BEE_PET(new String[] { "addperm %player% pets.use.bee" }, Material.PLAYER_HEAD, "&e&lBee Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmQxNjU4ZmQ0OTRmOGUyMjkwZGI0MWRjNGQxMWQ0NjdjMjU5NjFlZGNhNjMzMTdlOGY5OTcxZWIyOGE0N2NjNSJ9fX0=", 0),
    PLAYFUL_PANDA_PET(new String[] { "addperm %player% pets.use.panda", "addperm %player% pets.use.playful_panda" }, Material.PLAYER_HEAD, "&e&lPlayful Panda Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGYwMDg1ODkyNmNkOGNkZjNmMWNmNzFlMjEwY2RlNWRhZjg3MDgzMjA1NDdiZDZkZjU3OTU4NTljNjhkOWIzZiJ9fX0=", 0),
    BROWN_PANDA_PET(new String[] { "addperm %player% pets.use.panda", "addperm %player% pets.use.brown_panda" }, Material.PLAYER_HEAD, "&e&lBrown Panda Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzVkMGQ0NWJmOTkyYjA3MmNmNWM1MTNlMDZiZWVmZThiZGM4MDljODE1MGYzZDE0Yjg4Mzc5NmE3Yjc0ZTQwNiJ9fX0=", 0),
    RED_FOX_PET(new String[] { "addperm %player% pets.use.fox", "addperm %player% pets.use.red_fox" }, Material.PLAYER_HEAD, "&e&lRed Fox Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzVkMGQ0NWJmOTkyYjA3MmNmNWM1MTNlMDZiZWVmZThiZGM4MDljODE1MGYzZDE0Yjg4Mzc5NmE3Yjc0ZTQwNiJ9fX0=", 0),
    SNOW_FOX_PET(new String[] { "addperm %player% pets.use.fox", "addperm %player% pets.use.snow_fox" }, Material.PLAYER_HEAD, "&e&lSnow Fox Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDE0MzYzNzdlYjRjNGI0ZTM5ZmIwZTFlZDg4OTlmYjYxZWUxODE0YTkxNjliOGQwODcyOWVmMDFkYzg1ZDFiYSJ9fX0=", 0),
    BROWN_RABBIT_PET(new String[] { "addperm %player% pets.use.rabbit", "addperm %player% pets.use.brown_rabbit" }, Material.PLAYER_HEAD, "&e&lBrown Rabbit Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmZlY2M2YjVlNmVhNWNlZDc0YzQ2ZTc2MjdiZTNmMDgyNjMyN2ZiYTI2Mzg2YzZjYzc4NjMzNzJlOWJjIn19fQ==", 0),
    WHITE_RABBIT_PET(new String[] { "addperm %player% pets.use.rabbit", "addperm %player% pets.use.white_rabbit" }, Material.PLAYER_HEAD, "&e&lWhite Rabbit Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjRkY2ZlZDY4OTdhMThhN2FiOTk1YTY2MTM0ZDQxYTFjYTgyMWI2OWJjYjdkMTRjZjI2OWI0YTk4ZGY0OWE4In19fQ==", 0),
    BLACK_RABBIT_PET(new String[] { "addperm %player% pets.use.rabbit", "addperm %player% pets.use.black_rabbit" }, Material.PLAYER_HEAD, "&e&lBlack Rabbit Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzJjNTgxMTZhMTQ3ZDFhOWEyNjI2OTIyNGE4YmUxODRmZThlNWYzZjNkZjliNjE3NTEzNjlhZDg3MzgyZWM5In19fQ==", 0),
    BLACK_AND_WHITE_RABBIT_PET(new String[] { "addperm %player% pets.use.rabbit", "addperm %player% pets.use.black_and_white_rabbit" }, Material.PLAYER_HEAD, "&e&lBlack And White Rabbit Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2I4Y2ZmNGIxNWI4Y2EzN2UyNTc1MGYzNDU3MThmMjg5Y2IyMmM1YjNhZDIyNjI3YTcxMjIzZmFjY2MifX19", 0),
    GOLD_RABBIT_PET(new String[] { "addperm %player% pets.use.rabbit", "addperm %player% pets.use.gold_rabbit" }, Material.PLAYER_HEAD, "&e&lGold Rabbit Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzk3N2EzMjY2YmYzYjllYWYxN2U1YTAyZWE1ZmJiNDY4MDExNTk4NjNkZDI4OGI5M2U2YzEyYzljYiJ9fX0=", 0),
    CREAMY_HORSE_PET(new String[] { "addperm %player% pets.use.horse", "addperm %player% pets.use.creamy_horse" }, Material.PLAYER_HEAD, "&e&lCreamy Horse Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTZkYWUwYWRlMGUwZGFmYjZkYmM3Nzg2Y2U0MjQxMjQyYjZiNmRmNTI3YTBmN2FmMGE0MjE4NGM5M2ZkNjQ2YiJ9fX0=", 0),
    WHITE_HORSE_PET(new String[] { "addperm %player% pets.use.horse", "addperm %player% pets.use.white_horse" }, Material.PLAYER_HEAD, "&e&lWhite Horse Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjBhMmRiMmYxZWI5M2U1OTc4ZDJkYzkxYTc0ZGY0M2Q3Yjc1ZDllYzBlNjk0ZmQ3ZjJhNjUyZmJkMTUifX19", 0),
    BROWN_HORSE_PET(new String[] { "addperm %player% pets.use.horse", "addperm %player% pets.use.brown_horse" }, Material.PLAYER_HEAD, "&e&lBrown Horse Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmVkZjczZWExMmNlNmJkOTBhNGFlOWE4ZDE1MDk2NzQ5Y2ZlOTE4MjMwZGM4MjliMjU4MWQyMjNiMWEyYTgifX19", 0),
    BLACK_HORSE_PET(new String[] { "addperm %player% pets.use.horse", "addperm %player% pets.use.black_horse" }, Material.PLAYER_HEAD, "&e&lBlack Horse Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjRiN2ZjNWY3YTlkZGZkZDFhYTc5MzE3NDEwZmMxOTI5ZjkxYmRkZjk4NTg1OTM4YTJhNTYxOTlhNjMzY2MifX19", 0),
    GRAY_HORSE_PET(new String[] { "addperm %player% pets.use.horse", "addperm %player% pets.use.gray_horse" }, Material.PLAYER_HEAD, "&e&lGray Horse Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDY2NzZjNGQ2ZjBmNWVkNjA2YTM1NmYzY2M1YTI5ZDE0YWFmZTY1NzIxYmExYTFhOTVjNWFjNGM1ZTIzOWU1In19fQ==", 0),
    DARK_BROWN_HORSE_PET(new String[] { "addperm %player% pets.use.horse", "addperm %player% pets.use.dark_brown_horse" }, Material.PLAYER_HEAD, "&e&lDark Brown Horse Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjY2MWYyM2ZiNzY2MjRmZmJhYmJkYTMxY2E0YTM4YjQwNGZlNjNlZjM3ZDRiYTRlNGM1NDQxYTIxZTNhNiJ9fX0=", 0),
    SKELETON_HORSE_PET(new String[] { "addperm %player% pets.use.horse", "addperm %player% pets.use.skeleton_horse" }, Material.PLAYER_HEAD, "&e&lSkeleton Horse Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDdlZmZjZTM1MTMyYzg2ZmY3MmJjYWU3N2RmYmIxZDIyNTg3ZTk0ZGYzY2JjMjU3MGVkMTdjZjg5NzNhIn19fQ==", 0),
    ZOMBIE_HORSE_PET(new String[] { "addperm %player% pets.use.horse", "addperm %player% pets.use.zombie_horse" }, Material.PLAYER_HEAD, "&e&lZombie Horse Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDIyOTUwZjJkM2VmZGRiMThkZTg2ZjhmNTVhYzUxOGRjZTczZjEyYTZlMGY4NjM2ZDU1MWQ4ZWI0ODBjZWVjIn19fQ==", 0),
    DONKEY_PET(new String[] { "addperm %player% pets.use.donkey" }, Material.PLAYER_HEAD, "&e&lDonkey Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzk5YmI1MGQxYTIxNGMzOTQ5MTdlMjViYjNmMmUyMDY5OGJmOThjYTcwM2U0Y2MwOGI0MjQ2MmRmMzA5ZDZlNiJ9fX0=", 0),
    LEUCISTIC_AXOLOTL_PET(new String[] { "addperm %player% pets.use.axolotl", "addperm %player% pets.use.leucistic_axolotl" }, Material.PLAYER_HEAD, "&e&lLeucistic Axolotl Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2I4M2EzOGE0NThjM2NjYTA3NjFlMmM4MjEwYzZmNWQyZjMzODBlODYwZDUwZDJmNDc1NjUxNmEyNjQyNjE3ZCJ9fX0=", 0),
    BLUE_AXOLOTL_PET(new String[] { "addperm %player% pets.use.axolotl", "addperm %player% pets.use.blue_axolotl" }, Material.PLAYER_HEAD, "&e&lBlue Axolotl Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWVmNjMwNjU3ZTRhMjc5YjBiN2VhMGY2NzkwNTkyMGFmMzY1ZjljODRjYTlmMzRhMzJiNTMzNDNmZjYyOTkxMCJ9fX0=", 0),
    CYAN_AXOLOTL_PET(new String[] { "addperm %player% pets.use.axolotl", "addperm %player% pets.use.cyan_axolotl" }, Material.PLAYER_HEAD, "&e&lCyan Axolotl Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTFjMmQwYzNiOTZhZDQ1YjQ2NjM4OGUwMjhiMjQ3YWFmZTM2YjI2YjEyYzQxMWVjYjcyZTliNTBlYTIxZTUyYyJ9fX0=", 0),
    GOLD_AXOLOTL_PET(new String[] { "addperm %player% pets.use.axolotl", "addperm %player% pets.use.gold_axolotl" }, Material.PLAYER_HEAD, "&e&lGold Axolotl Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2Y4MGNjMTQ5MmU0NDY2OGNjY2RiNDAxNzhjM2E2Njg5ZThkZmMwZDIzNGU5ODU1M2ZiN2RlYmMyNmZjYWVhYyJ9fX0=", 0),
    WILD_AXOLOTL_PET(new String[] { "addperm %player% pets.use.axolotl", "addperm %player% pets.use.wild_axolotl" }, Material.PLAYER_HEAD, "&e&lWild Axolotl Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGQ3ZWZlMDIwMTJjZjMxYWUyNzA4ZTdkN2RmMDc5NzI2NTc1YzdlZTg1MDQzMjgxNzVmZTU0NDcwODE4N2RjZSJ9fX0=", 0),
    GOAT_PET(new String[] { "addperm %player% pets.use.goat" }, Material.PLAYER_HEAD, "&e&lGoat Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTY2MjMzNmQ4YWUwOTI0MDdlNThmN2NjODBkMjBmMjBlNzY1MDM1N2E0NTRjZTE2ZTMzMDc2MTlhMDExMDY0OCJ9fX0=", 0),
    SNOWMAN_PET(new String[] { "addperm %player% pets.use.snowman" }, Material.PLAYER_HEAD, "&e&lSnowman Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTExMzY2MTZkOGM0YTg3YTU0Y2U3OGE5N2I1NTE2MTBjMmIyYzhmNmQ0MTBiYzM4Yjg1OGY5NzRiMTEzYjIwOCJ9fX0=", 0),
    ZOMBIE_PET(new String[] { "addperm %player% pets.use.zombie" }, Material.PLAYER_HEAD, "&e&lZombie Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTZmYzg1NGJiODRjZjRiNzY5NzI5Nzk3M2UwMmI3OWJjMTA2OTg0NjBiNTFhNjM5YzYwZTVlNDE3NzM0ZTExIn19fQ==", 0),
    ZOGLIN_PET(new String[] { "addperm %player% pets.use.zoglin" }, Material.PLAYER_HEAD, "&e&lZoglin Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTY3ZTE4NjAyZTAzMDM1YWQ2ODk2N2NlMDkwMjM1ZDg5OTY2NjNmYjllYTQ3NTc4ZDNhN2ViYmM0MmE1Y2NmOSJ9fX0=", 0),
    ENDERMITE_PET(new String[] { "addperm %player% pets.use.zoglin" }, Material.PLAYER_HEAD, "&e&lEndermite Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWJjN2I5ZDM2ZmI5MmI2YmYyOTJiZTczZDMyYzZjNWIwZWNjMjViNDQzMjNhNTQxZmFlMWYxZTY3ZTM5M2EzZSJ9fX0=", 0),
    SILVERFISH_PET(new String[] { "addperm %player% pets.use.silverfish" }, Material.PLAYER_HEAD, "&e&lSilverfish Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGE5MWRhYjgzOTFhZjVmZGE1NGFjZDJjMGIxOGZiZDgxOWI4NjVlMWE4ZjFkNjIzODEzZmE3NjFlOTI0NTQwIn19fQ==", 0),
    COLD_FROG_PET(new String[] { "addperm %player% pets.use.frog", "addperm %player% pets.use.cold_frog" }, Material.PLAYER_HEAD, "&e&lCold Frog Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2U2MmU4YTA0OGQwNDBlYjA1MzNiYTI2YTg2NmNkOWMyZDA5MjhjOTMxYzUwYjQ0ODJhYzNhMzI2MWZhYjZmMCJ9fX0=", 0),
    TEMPERATE_FROG_PET(new String[] { "addperm %player% pets.use.frog", "addperm %player% pets.use.temperate_frog" }, Material.PLAYER_HEAD, "&e&lTemperate Frog Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjNjZTZmOTk5OGVkMmRhNzU3ZDFlNjM3MmYwNGVmYTIwZTU3ZGZjMTdjM2EwNjQ3ODY1N2JiZGY1MWMyZjJhMiJ9fX0=", 0),
    WARM_FROG_PET(new String[] { "addperm %player% pets.use.frog", "addperm %player% pets.use.warm_frog" }, Material.PLAYER_HEAD, "&e&lWarm Frog Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjc3MzE0ZmEwMzhlYzMxMzU3ODQ1YTkzMjc0YjRkYzg4NDEyNDY4NjcyOGZmZTBkZWQ5YzM1NDY2YWNhMGFhYiJ9fX0=", 0),
    ALLAY_PET(new String[] { "addperm %player% pets.use.allay" }, Material.PLAYER_HEAD, "&e&lAllay Pet", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTUwMjk0YTE3NDczMTBmMTA0MTI0YzYzNzNjYzYzOWI3MTJiYWE1N2I3ZDkyNjI5N2I2NDUxODhiN2JiOWFiOSJ9fX0=", 0),

    //trails
    VILLAGER_HAPPY_TRAIL(new String[] { "addperm %player% trails.use.villager_happy" }, Material.PLAYER_HEAD, "&e&lVillager Happy Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTI4Mzk2NTkyM2MwZTNlYWQwZmU4NzYwZTA4Y2JhODk4MmUzM2E2YWNkYjg5MWVjYzZmNmRmZTZkNWQxODBiYyJ9fX0=", 0),
    VILLAGER_ANGRY_TRAIL(new String[] { "addperm %player% trails.use.villager_angry" }, Material.PLAYER_HEAD, "&e&lVillager Angry Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmFiZWMyNDBhNGNiNTFjYWRjMTg1YTY2MDcyYTJhZWQ3ZjU2MTEyNjk2ZjI0NjU3M2E1MmVlN2RmNGMzMiJ9fX0=", 0),
    REDSTONE_TRAIL(new String[] { "addperm %player% trails.use.redstone" }, Material.PLAYER_HEAD, "&e&lRedstone Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmIyYzI2NzhlOTM2NDA5ODhlNjg1YWM4OTM0N2VmYTQ1MjQxMTljOWQ4ZjcyNzhjZTAxODFiYzNlNGZiMmIwOSJ9fX0=", 0),
    TOTEM_TRAIL(new String[] { "addperm %player% trails.use.totem" }, Material.PLAYER_HEAD, "&e&lTotem Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTFkMWNmMjg5MTY1ZmJiMTEyZDg5MjFkNDc3MDhlNDlmYjcwOTI1NzM5YjFjYmQxNzk4ZGFmZjQyMjgwNmU4YSJ9fX0=", 0),
    CLOUD_TRAIL(new String[] { "addperm %player% trails.use.cloud" }, Material.PLAYER_HEAD, "&e&lCloud Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDY2YjEwYmY2ZWUyY2Q3ZTNhYzk2ZDk3NDllYTYxNmFhOWM3MzAzMGJkY2FlZmZhZWQyNDllNTVjODQ5OTRhYyJ9fX0=", 0),
    CAMPFIRE_COSY_SMOKE_TRAIL(new String[] { "addperm %player% trails.use.campfire_cosy_smoke" }, Material.PLAYER_HEAD, "&e&lCampfire Cosy Smoke Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmQ5NTk2NWQ3OWRkZjYxM2Y1OTRmZDIwZDUxZTc2NWMwOWEyYTVmZjhkMGUwOWNmZjE5YThlYTQzMDIzNThhZCJ9fX0=", 0),
    FALLING_SPORE_BLOSSOM_TRAIL(new String[] { "addperm %player% trails.use.falling_spore_blossom" }, Material.PLAYER_HEAD, "&e&lFalling Spore Blossom Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjg2YWIwNTI0OTAwNzZlMzZiMzM2NjcyMWI2M2NkMDNiNzA0ZjIzZWQ3ZTMwMGM3MTU4NGJkMzg2OTBhMDk0NiJ9fX0=", 0),
    GLOW_SQUID_INK_TRAIL(new String[] { "addperm %player% trails.use.glow_squid_ink" }, Material.PLAYER_HEAD, "&e&lGlow Squid Ink Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmM3ZGVhZjJkN2U3MmYyMWZjYTNhOTk2OTQ0ODFhNjc0ZjUxODVjNDRjM2I4ZjUzYjBiNDkzMTBmZTYxNzY3ZCJ9fX0=", 0),
    SCRAPE_TRAIL(new String[] { "addperm %player% trails.use.scrape" }, Material.PLAYER_HEAD, "&e&lScrape Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTYxM2Y2MGU2ZWNmNmMyMWQ5MzA2NmIxYmQ2ZjdjNGI3YzQ4OGU2OGE2NDI1MTQ1Njc3Y2M2ZDVkYTMzYmE0OSJ9fX0=", 0),
    DAMAGE_INDICATOR_TRAIL(new String[] { "addperm %player% trails.use.damage_indicator" }, Material.PLAYER_HEAD, "&e&lDamage Indicator Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWVlMTE4ZWRkYWVlMGRmYjJjYmMyYzNkNTljMTNhNDFhN2Q2OGNjZTk0NWU0MjE2N2FhMWRjYjhkMDY3MDUxNyJ9fX0=", 0),
    DRAGON_BREATH_TRAIL(new String[] { "addperm %player% trails.use.dragon_breath" }, Material.PLAYER_HEAD, "&e&lDragon Breath Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTFjZDZkMmQwM2YxMzVlN2M2YjVkNmNkYWUxYjNhNjg3NDNkYjRlYjc0OWZhZjczNDFlOWZiMzQ3YWEyODNiIn19fQ==", 0),
    ENCHANTMENT_TABLE_TRAIL(new String[] { "addperm %player% trails.use.enchantment_table" }, Material.PLAYER_HEAD, "&e&lEnchantment Table Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjJmNzkwMTZjYWQ4NGQxYWUyMTYwOWM0ODEzNzgyNTk4ZTM4Nzk2MWJlMTNjMTU2ODI3NTJmMTI2ZGNlN2EifX19", 0),
    SQUID_INK_TRAIL(new String[] { "addperm %player% trails.use.squid_ink" }, Material.PLAYER_HEAD, "&e&lSquid Ink Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDBmYjg3OGFhMjhiZGQ3NzQ1ZDM4Mjg2MTFkNzI2ZDk2NDYxNDQxZTA2MjY4OWIyODY2YmNmYTkwYjU5YjAwMyJ9fX0=", 0),
    FLAME_TRAIL(new String[] { "addperm %player% trails.use.flame" }, Material.PLAYER_HEAD, "&e&lFlame Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDA4MGJiZWZjYTg3ZGMwZjM2NTM2YjY1MDg0MjVjZmM0Yjk1YmE2ZThmNWU2YTQ2ZmY5ZTljYjQ4OGE5ZWQifX19", 0),
    SOUL_FIRE_FLAME_TRAIL(new String[] { "addperm %player% trails.use.soul_fire_flame" }, Material.PLAYER_HEAD, "&e&lSoul Fire Flame Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjE0NmI5NmU0MzEwMTllNzEzYmUzNmQwZTNhYzFkNDg0ZDNiY2U3MjNmNDRlOGJmZTM1YmVlN2NkMGY0NzkzNCJ9fX0=", 0),
    SPELL_WITCH_TRAIL(new String[] { "addperm %player% trails.use.spell_witch" }, Material.PLAYER_HEAD, "&e&lSpell Witch Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODU1YWY2YzVmZjIxZWI1NTYzMWEyNTIyMWQ3NTNjZGM5YTBmNjc5ZDVjYWNmNTU1YjM1MGJhMGUzNTIxZTA5MiJ9fX0=", 0),
    ASH_TRAIL(new String[] { "addperm %player% trails.use.ash" }, Material.PLAYER_HEAD, "&e&lAsh Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmIwMjU1YjY4NmVkZmY3OGZmODczMjY0NDFlZDhhZjhhZGExNTM4MjFkODNmMDE1OGU1NzM1YzZiODM5ZGFmOCJ9fX0=", 0),
    END_ROD_TRAIL(new String[] { "addperm %player% trails.use.end_rod" }, Material.PLAYER_HEAD, "&e&lEnd Rod Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDgwYjNkMDE5Y2NhMzY3Y2UzY2E2ZjE4MmZjZjkxYWM5YjhmYjBiZTI5YWZjZWRmZTU1OGVjZWUyMGI4MTdkZSJ9fX0=", 0),
    CRIT_TRAIL(new String[] { "addperm %player% trails.use.crit" }, Material.PLAYER_HEAD, "&e&lCrit Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDZjYzZiODM3NjNhNjdmY2FkYTFlYTE4NGMyZDE3NTJhZDI0MDc0NmM2YmUyNThhNzM5ODNkOGI2NTdmNGJiNSJ9fX0=", 0),
    CRIT_MAGIC_TRAIL(new String[] { "addperm %player% trails.use.crit_magic" }, Material.PLAYER_HEAD, "&e&lCrit Magic Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTg4MzJjMTQ2NmM4NDFjYzc5ZDVmMTAyOTVkNDY0Mjc5OTY3OTc1YTI0NTFjN2E1MzNjNzk5Njg5NzQwOGJlYSJ9fX0=", 0),
    DRIP_LAVA_TRAIL(new String[] { "addperm %player% trails.use.drip_lava" }, Material.PLAYER_HEAD, "&e&lDrip Lava Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjY5NjVlNmE1ODY4NGMyNzdkMTg3MTdjZWM5NTlmMjgzM2E3MmRmYTk1NjYxMDE5ZGJjZGYzZGJmNjZiMDQ4In19fQ==", 0),
    DRIP_WATER_TRAIL(new String[] { "addperm %player% trails.use.drip_water" }, Material.PLAYER_HEAD, "&e&lDrip Water Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzRmY2JjMjU2ZDBiZTdlNjgzYWY4NGUzOGM0YmNkYjcxYWZiOTM5ODUzOGEyOWFhOTZjYmZhMzE4YjJlYSJ9fX0=", 0),
    DRIPPING_OBSIDIAN_TEAR_TRAIL(new String[] { "addperm %player% trails.use.dripping_obsidian_tear" }, Material.PLAYER_HEAD, "&e&lDripping Obsidian Tear Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGE1Yzg2ODY0MTFkNDQ2YzkwYzE5MWM5M2Y4MGI5ZmZiMWNkMjQ3YWExMmEyMjZmODk3OTk4MWFkNDM4OGJlZSJ9fX0=", 0),
    PORTAL_TRAIL(new String[] { "addperm %player% trails.use.portal" }, Material.PLAYER_HEAD, "&e&lPortal Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzNhOGU0MDJkYWQxYjdkYWQ5YWFlNmY0MDE1OTMyMTgzNDI5Y2U4N2JiYmVjZWQzMTE5MDI2ZjgyOTYzMzZjMiJ9fX0=", 0),
    SLIME_TRAIL(new String[] { "addperm %player% trails.use.slime" }, Material.PLAYER_HEAD, "&e&lSlime Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7ImlkIjoiNDU5ZmNiYmMyNGZjNGE4YmJiYmYyYTExM2E0YzFjNGEiLCJ0eXBlIjoiU0tJTiIsInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmIxZTc5NTdmZWI4NTUxMjQxZmExZTkxODEzNTZiYzBkZjU2YTIzMzIzNjE0YTg4Y2E1ZmVkNGRjYmY2YzJlIiwicHJvZmlsZUlkIjoiODAxOGFiMDBiMmFlNDRjYWFjOWJmNjBlZjkwZjQ1ZTUiLCJ0ZXh0dXJlSWQiOiI2YjFlNzk1N2ZlYjg1NTEyNDFmYTFlOTE4MTM1NmJjMGRmNTZhMjMzMjM2MTRhODhjYTVmZWQ0ZGNiZjZjMmUifX0sInNraW4iOnsiaWQiOiI0NTlmY2JiYzI0ZmM0YThiYmJiZjJhMTEzYTRjMWM0YSIsInR5cGUiOiJTS0lOIiwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82YjFlNzk1N2ZlYjg1NTEyNDFmYTFlOTE4MTM1NmJjMGRmNTZhMjMzMjM2MTRhODhjYTVmZWQ0ZGNiZjZjMmUiLCJwcm9maWxlSWQiOiI4MDE4YWIwMGIyYWU0NGNhYWM5YmY2MGVmOTBmNDVlNSIsInRleHR1cmVJZCI6IjZiMWU3OTU3ZmViODU1MTI0MWZhMWU5MTgxMzU2YmMwZGY1NmEyMzMyMzYxNGE4OGNhNWZlZDRkY2JmNmMyZSJ9LCJjYXBlIjpudWxsfQ==", 0),
    FIREWORKS_SPARK_TRAIL(new String[] { "addperm %player% trails.use.fireworks_spark" }, Material.PLAYER_HEAD, "&e&lFireworks Spark Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU3NTJjOGY0MjIwZTJiM2UzOTc1NTU2ODQ1NDYwNjEzYWFlYjRkYjBjNjRiYTFjZTk2ZmFiZjNkNmVjMzVkYyJ9fX0=", 0),
    SNOWFLAKE_TRAIL(new String[] { "addperm %player% trails.use.snowflake" }, Material.PLAYER_HEAD, "&e&lSnowflake Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWRmZDc3MjRjNjlhMDI0ZGNmYzYwYjE2ZTAwMzM0YWI1NzM4ZjRhOTJiYWZiOGZiYzc2Y2YxNTMyMmVhMDI5MyJ9fX0=", 0),
    NOTE_TRAIL(new String[] { "addperm %player% trails.use.note" }, Material.PLAYER_HEAD, "&e&lNote Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTYyMGI4MmNmMTFlM2MxMzcxY2M1MWViOWUzMTJkZTcyYTZhNjI2NjQ0OTRlZDJjYjcxODFiMWJkZmJjOTI3OCJ9fX0=", 0),
    HEART_TRAIL(new String[] { "addperm %player% trails.use.heart" }, Material.PLAYER_HEAD, "&e&lHeart Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODU0MzE1OWZhN2ZmOGI1M2MyY2I4ZjMzYzQxYTM3N2FlZDZhY2U4MjY0NWM5Mzg1NjgzMDRkZDFjMzQifX19", 0),
    NAUTILUS_TRAIL(new String[] { "addperm %player% trails.use.nautilus" }, Material.PLAYER_HEAD, "&e&lNautilus Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTI5NWExMWVlNjE5ZWQ1NzYxYmY3YTdlYTE5MGM3NWQyYmVlYjdkZWYxYjE1NWRlNjAzZmYyMTdhNmM4NzEyNyJ9fX0=", 0),
    GLOW_TRAIL(new String[] { "addperm %player% trails.use.glow" }, Material.PLAYER_HEAD, "&e&lGlow Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNmOWJmZDIxMmIwOTk2NDEzMmQxNDAzNzc0ZTdmMWJmODljNDZiYjU2ODc5NmE4OGY5NDZkODYyYWJhYmIwOSJ9fX0=", 0),
    SPIT_TRAIL(new String[] { "addperm %player% trails.use.spit" }, Material.PLAYER_HEAD, "&e&lSpit Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDY2YjEwYmY2ZWUyY2Q3ZTNhYzk2ZDk3NDllYTYxNmFhOWM3MzAzMGJkY2FlZmZhZWQyNDllNTVjODQ5OTRhYyJ9fX0=", 0),
    SNEEZE_TRAIL(new String[] { "addperm %player% trails.use.sneeze" }, Material.PLAYER_HEAD, "&e&lSneeze Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGYwYzQ4MDQzYjIxNTk5NDhlODFjYzU3NWUzZDY5MmFkYjFkNzNiMjViZDAxZDlmNzhiYTg5MmE5NDQ0ZTQyMCJ9fX0=", 0),
    WAX_ON_TRAIL(new String[] { "addperm %player% trails.use.wax_on" }, Material.PLAYER_HEAD, "&e&lWax On Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2U0MjNlODM2OGMyNTYwZTJmMDVkOTVkMzY5MzgxZWYxZmE0MGI4NTQ2ODc4MWYyMTlkZGVjZWNkZDcwZjRkZSJ9fX0=", 0),
    WAX_OFF_TRAIL(new String[] { "addperm %player% trails.use.wax_off" }, Material.PLAYER_HEAD, "&e&lWax Off Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTQ4NjE2N2UwZTUwMTcwM2VmMzAyNDkxYjA0Yjc4Y2ViNGVlOWM1ODczMTY2ZmQ3NWFjNWRlMTFhOTRhOTdmOSJ9fX0=", 0),
    SCULK_CHARGE_POP_TRAIL(new String[] { "addperm %player% trails.use.sculk_charge_pop" }, Material.PLAYER_HEAD, "&e&lSculk Charge Pop Trail", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTZkY2UyMzliYjQwMTNiMmI3ZGVlMDU0MGEwNDcyZTAyNzg3YmQyZTUwMDJiZTY5MzNmNGEwNTY2Zjc3MTNiNSJ9fX0=", 0),

    //trail styles
    TWINS_TRAIL_STYLE(new String[] { "addperm %player% trails.use.twins" }, Material.PLAYER_HEAD, "&e&lTwins Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2NjODEyZWNiYzFkZWM2ZTNkY2FiZWM1MmVhN2VkMjNkYTJjZDU0NDRhMDFkNGFkZDEzMmJjN2FlYzM4NDEifX19", 0),
    HELIX_TRAIL_STYLE(new String[] { "addperm %player% trails.use.helix" }, Material.PLAYER_HEAD, "&e&lHelix Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDdhNGFmMGU0ZjQ5NDFlM2Y5ZDBiNTcwZDA5NzkwOTQ0MDY2YWM5NjMxMmFhZWFmMGNhODhhOTk5MmU1In19fQ==", 0),
    SPINNING_HELIX_STYLE(new String[] { "addperm %player% trails.use.spinning_helix" }, Material.PLAYER_HEAD, "&e&lSpinning Helix Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWQ3ZTc3MmM5Mjk1NDUzYzZhYTYyNDVmZmI0MDJmZGY2NzExMWI5NjE3OTE4OWJkMzBlMzY2NmY5NThiOTkifX19", 0),
    CONE_STYLE(new String[] { "addperm %player% trails.use.cone" }, Material.PLAYER_HEAD, "&e&lCone Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjRhMDZiYWNkYmM5YWI4ZDljYzgzZGQ4MzYyMjM3YjRkMzk3MTUxNDI5N2JhNjQ1ZWVmODIyOGE3NjE0MzEifX19", 0),
    SPHERE_STYLE(new String[] { "addperm %player% trails.use.sphere" }, Material.PLAYER_HEAD, "&e&lSphere Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWRkYzk5Yjg2OTVjMjkwNmE0Mzc0YTg2OGFhMWU1OGYwZjcxMTdlMWE4YTlmZWEyNzNhOTFhODk1ZDY2YTQifX19", 0),
    HALO_STYLE(new String[] { "addperm %player% trails.use.halo" }, Material.PLAYER_HEAD, "&e&lHalo Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmIxNzg2NjkyNzU5NDZmZmEwYTc4MDc0ZGQ3NDY4MzQ3MTQxZDBhMjg1NGMzOTliYTc5ZTU0OGFmYjQ2YyJ9fX0=", 0),
    SPIRAL_STYLE(new String[] { "addperm %player% trails.use.spiral" }, Material.PLAYER_HEAD, "&e&lSpiral Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjY4ZGZkODdjNzVhMDU0NGUxNzZjYzAzYThiODIyZjJhNjQyY2NkYTk0NjI0Njk1NTY5MmNmNDljOTQ2ZDkifX19", 0),
    BLOCK_BREAK_STYLE(new String[] { "addperm %player% trails.use.block_break" }, Material.PLAYER_HEAD, "&e&lBlock Break Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWM4ZDk3NDgzOGQ3OTdiOGU4NzNkYzc4MTQxNzE1ZDU0MjE5ZDIwYTg0YzFjODM5YmU4MDM0ZTQxNDMwIn19fQ==", 0),
    ARROW_SHOOT_STYLE(new String[] { "addperm %player% trails.use.arrow_shoot" }, Material.PLAYER_HEAD, "&e&lArrow Shoot Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmU5N2Y3ZTVmZWQ1YmJlOTY0MTVlMTU1ODc3NmNhNDlmNGM5NWU5OGM3Mjk5ODZkZjNlZGE4MjE0Yzg4YyJ9fX0=", 0),
    TRIDENT_THROW_STYLE(new String[] { "addperm %player% trails.use.trident_throw" }, Material.PLAYER_HEAD, "&e&lTrident Throw Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjNjZmQyZTljYjdlOGE2NzVjNDg4N2I1NDI2NGU5ZDYyNWNmNmM2ZGIyY2ZjNTc3ZDJhN2I1YTMyZjIwZWUifX19", 0),
    SNOWBALL_THROW_STYLE(new String[] { "addperm %player% trails.use.snowball_throw" }, Material.PLAYER_HEAD, "&e&lSnowball Throw Trail Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjNjZmQyZTljYjdlOGE2NzVjNDg4N2I1NDI2NGU5ZDYyNWNmNmM2ZGIyY2ZjNTc3ZDJhN2I1YTMyZjIwZWUifX19", 0),
    ENDER_PEARL_THROW_STYLE(new String[] { "addperm %player% trails.use.ender_pearl_throw" }, Material.PLAYER_HEAD, "&e&lEnder Pearl Throw Style", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmM2MDc1Y2FjN2QyZDVhYmM1NWIzMzkyNTY2ZDRhZGM1MjhkNDgxZjc3YmVjMGRlZjEzODVjOGJkYjIwNmM1NiJ9fX0=", 0),

    //skins

    //swords
    GALAXY_BLADE_SKIN(new String[] { "giveskin GALAXY_BLADE %player%" }, Material.DIAMOND_SWORD, "&e&lGalaxy Blade Skin", null, 4001),
    CRYSTAL_SWORD_SKIN(new String[] { "giveskin CRYSTAL_SWORD %player%" }, Material.DIAMOND_SWORD, "&e&lCrystal Sword Skin", null, 4002),
    GREATSWORD_OF_THE_HIDDEN_FOREST_SKIN(new String[] { "giveskin GREATSWORD_OF_THE_HIDDEN_FOREST %player%" }, Material.DIAMOND_SWORD, "&e&lGreatsword Of The Hidden Forest Skin", null, 4003),
    MOLTEN_CHAOS_SWORD_SKIN(new String[] { "giveskin MOLTEN_CHAOS_SWORD %player%" }, Material.DIAMOND_SWORD, "&e&lMolten Chaos Sword Skin", null, 4004),
    STEEL_SNAKE_SWORD_SKIN(new String[] { "giveskin STEEL_SNAKE_SWORD %player%" }, Material.DIAMOND_SWORD, "&e&lSteel Snake Sword Skin", null, 4005),
    ZEPHYR_SWORD_SKIN(new String[] { "giveskin ZEPHYR_SWORD %player%" }, Material.DIAMOND_SWORD, "&e&lZephyr Sword Skin", null, 4006),
    BUBBLE_CORAL_BLADE_SKIN(new String[] { "giveskin BUBBLE_CORAL_BLADE %player%" }, Material.DIAMOND_SWORD, "&e&lBubble Coral Blade Skin", null, 4007),
    DRAGON_SLAYER_SWORD_SKIN(new String[] { "giveskin DRAGON_SLAYER_SWORD %player%" }, Material.DIAMOND_SWORD, "&e&lDragon Slayer Sword Skin", null, 4008),
    EYE_OF_THE_END_SWORD_SKIN(new String[] { "giveskin EYE_OF_THE_END_SWORD %player%" }, Material.DIAMOND_SWORD, "&e&lEye Of The End Sword Skin", null, 4009),
    AZURE_GREATSWORD_SWORD_SKIN(new String[] { "giveskin AZURE_GREATSWORD %player%" }, Material.DIAMOND_SWORD, "&e&lAzure Greatsword Skin", null, 4010),
    RUNIC_PIERCER_SWORD_SKIN(new String[] { "giveskin RUNIC_PIERCER_SWORD %player%" }, Material.DIAMOND_SWORD, "&e&lRunic Piercer Sword Skin", null, 4011),
    DEATH_BLUDGEON_SKIN(new String[] { "giveskin DEATH_BLUDGEON %player%" }, Material.DIAMOND_SWORD, "&e&lDeath Bludgeon Skin", null, 4012),
    SOUL_DESTROYER_BLADE_SKIN(new String[] { "giveskin SOUL_DESTROYER_BLADE %player%" }, Material.DIAMOND_SWORD, "&e&lSoul Destroyer Blade Skin", null, 4013),
    CRIMSON_CLEAVER_SKIN(new String[] { "giveskin CRIMSON_CLEAVER %player%" }, Material.DIAMOND_SWORD, "&e&lCrimson Cleaver Skin", null, 4014),
    GOLDEN_GLORY_BLADE_SKIN(new String[] { "giveskin GOLDEN_GLORY_BLADE %player%" }, Material.DIAMOND_SWORD, "&e&lGolden Glory Skin", null, 4015),

    //bows
    PHANTOM_BOW_SKIN(new String[] { "giveskin PHANTOM_BOW %player%" }, Material.BOW, "&e&lPhantom Bow Skin", null, 5000),
    DEVILS_STING_BOW_SKIN(new String[] { "giveskin DEVILS_STING_BOW %player%" }, Material.BOW, "&e&lDevil's Sting Bow Skin", null, 5001),
    QUICKSTRIKE_BOW_SKIN(new String[] { "giveskin QUICKSTRIKE_BOW %player%" }, Material.BOW, "&e&lQuickstrike Bow Skin", null, 5002),
    RAIN_DROP_BOW_SKIN(new String[] { "giveskin RAIN_DROP_BOW %player%" }, Material.BOW, "&e&lRain Drop Bow Skin", null, 5003),
    WORLDSHAPER_STAFF_SKIN(new String[] { "giveskin WORLDSHAPER_STAFF %player%" }, Material.BOW, "&e&lWorldshaper Staff Skin", null, 5004),
    SUNKEN_GEM_BOW_SKIN(new String[] { "giveskin SUNKEN_GEM_BOW %player%" }, Material.BOW, "&e&lSunken Gem Bow Skin", null, 5005),
    LAST_WHISPER_BOW_SKIN(new String[] { "giveskin LAST_WHISPER_BOW %player%" }, Material.BOW, "&e&lLast Whisper Bow Skin", null, 5006),

    //pickaxes
    FIERY_PICKAXE_SKIN(new String[] { "giveskin FIERY_PICKAXE %player%" }, Material.DIAMOND_PICKAXE, "&e&lFiery Pickaxe Skin", null, 6000),
    ORE_OBLITERATOR_PICKAXE_SKIN(new String[] { "giveskin ORE_OBLITERATOR_PICKAXE %player%" }, Material.DIAMOND_PICKAXE, "&e&lOre Obliterator Pickaxe Skin", null, 6001),
    PICK_OF_DESTINY_SKIN(new String[] { "giveskin PICK_OF_DESTINY %player%" }, Material.DIAMOND_PICKAXE, "&e&lPick Of Destiny Skin", null, 6002),
    HERO_OF_THE_VILLAGE_PICKAXE_SKIN(new String[] { "giveskin HERO_OF_THE_VILLAGE_PICKAXE %player%" }, Material.DIAMOND_PICKAXE, "&e&lHero Of The Village Pickaxe Skin", null, 6003),
    YURILILY_PICKAXE_SKIN(new String[] { "giveskin YURILILY_PICKAXE %player%" }, Material.DIAMOND_PICKAXE, "&e&lYurilily Pickaxe Skin", null, 6004),
    GRIM_VIOLET_PICKAXE_SKIN(new String[] { "giveskin GRIM_VIOLET_PICKAXE %player%" }, Material.DIAMOND_PICKAXE, "&e&lGrim Violet Skin", null, 6005),

    //axes
    AZURE_GREATAXE_SKIN(new String[] { "giveskin AZURE_GREATAXE %player%" }, Material.DIAMOND_AXE, "&e&lAzure Greataxe Skin", null, 7000),
    SKELETON_KING_AXE_SKIN(new String[] { "giveskin SKELETON_KING_AXE %player%" }, Material.DIAMOND_AXE, "&e&lSkeleton King Axe Skin", null, 7001),
    RUTHLESS_WAR_AXE_SKIN(new String[] { "giveskin RUTHLESS_WAR_AXE %player%" }, Material.DIAMOND_AXE, "&e&lRuthless War Axe Skin", null, 7002),
    HYPER_EDGE_AXE_SKIN(new String[] { "giveskin HYPER_EDGE_AXE %player%" }, Material.DIAMOND_AXE, "&e&lHyper Edge Axe Skin", null, 7003),
    FROST_AXE_SKIN(new String[] { "giveskin FROST_AXE %player%" }, Material.DIAMOND_AXE, "&e&lFrost Axe Skin", null, 7004),
    HOPES_END_AXE_SKIN(new String[] { "giveskin HOPES_END_AXE %player%" }, Material.DIAMOND_AXE, "&e&lHope's End Axe Skin", null, 7005),
    DEVOTION_AXE_SKIN(new String[] { "giveskin DEVOTION_AXE %player%" }, Material.DIAMOND_AXE, "&e&lDevotion Axe Skin", null, 7006),
    SLICE_OF_LIFE_AXE_SKIN(new String[] { "giveskin SLICE_OF_LIFE_AXE %player%" }, Material.DIAMOND_AXE, "&e&lSlice of Life Axe Skin", null, 7007),

    //hoes
    AZURE_SCYTHE_SKIN(new String[] { "giveskin AZURE_SCYTHE %player%" }, Material.DIAMOND_HOE, "&e&lAzure Scythe Skin", null, 8000),
    STEEL_LEAF_HOE_SKIN(new String[] { "giveskin STEEL_LEAF_HOE %player%" }, Material.DIAMOND_HOE, "&e&lSteel Leaf Hoe Skin", null, 8001),
    INFERNAL_HOE_SKIN(new String[] { "giveskin INFERNAL_HOE %player%" }, Material.DIAMOND_HOE, "&e&lInfernal Hoe Skin", null, 8002),
    DARK_MATTER_HOE_SKIN(new String[] { "giveskin DARK_MATTER_HOE %player%" }, Material.DIAMOND_HOE, "&e&lDark Matter Hoe Skin", null, 8003),
    ICE_STORM_HOE_SKIN(new String[] { "giveskin ICE_STORM_HOE %player%" }, Material.DIAMOND_HOE, "&e&lIce Storm Hoe Skin", null, 8004),
    AWAKENED_DEMONIC_SCYTHE_SKIN(new String[] { "giveskin AWAKENED_DEMONIC_SCYTHE %player%" }, Material.DIAMOND_HOE, "&e&lAwakened Demonic Scythe Skin", null, 8005),
    SPARKLE_SWEEP_HOE_SKIN(new String[] { "giveskin SPARKLE_SWEEP_HOE %player%" }, Material.DIAMOND_HOE, "&e&lSparkle Sweep Hoe Skin", null, 8006),

    //shovels
    TWILIGHT_SHOVEL_SKIN(new String[] { "giveskin TWILIGHT_SHOVEL %player%" }, Material.DIAMOND_SHOVEL, "&e&lTwilight Shovel Skin", null, 9000),
    RUBY_SHOVEL_SKIN(new String[] { "giveskin RUBY_SHOVEL %player%" }, Material.DIAMOND_SHOVEL, "&e&lRuby Shovel Skin", null, 9001),
    SCOOP_OF_HEAVEN_SHOVEL_SKIN(new String[] { "giveskin SCOOP_OF_HEAVEN_SHOVEL %player%" }, Material.DIAMOND_SHOVEL, "&e&lScoop Of Heaven Shovel Skin", null, 9002),
    LAST_RESORT_SHOVEL_SKIN(new String[] { "giveskin LAST_RESORT_SHOVEL %player%" }, Material.DIAMOND_SHOVEL, "&e&lLast Resort Shovel Skin", null, 9003),
    HEARTLESS_FOCUS_SHOVEL_SKIN(new String[] { "giveskin HEARTLESS_FOCUS_SHOVEL %player%" }, Material.DIAMOND_SHOVEL, "&e&lHeartless Focus Shovel Skin", null, 9004),
    FRENZY_SHOVEL_SKIN(new String[] { "giveskin FRENZY_SHOVEL %player%" }, Material.DIAMOND_SHOVEL, "&e&lFrenzy Shovel Skin", null, 9005),
    TWINKLE_SHOVEL_SKIN(new String[] { "giveskin TWINKLE_SHOVEL %player%" }, Material.DIAMOND_SHOVEL, "&e&lTwinkle Shovel Skin", null, 9006),

    //shield
    AWW_MAN_SHIELD_SKIN(new String[] { "giveskin AWW_MAN_SHIELD %player%" }, Material.SHIELD, "&e&lAww Man Shield Skin", null, 10000),
    WALL_OF_PAIN_SHIELD_SKIN(new String[] { "giveskin WALL_OF_PAIN_SHIELD %player%" }, Material.SHIELD, "&e&lWall Of Pain Shield Skin", null, 10001),
    REDEMPTION_SHIELD_SKIN(new String[] { "giveskin REDEMPTION_SHIELD %player%" }, Material.SHIELD, "&e&lRedemption Shield Skin", null, 10002),
    CLEAR_VIEW_SHIELD_SKIN(new String[] { "giveskin CLEAR_VIEW_SHIELD %player%" }, Material.SHIELD, "&e&lClear View Shield Skin", null, 10003),
    PRICKLY_STANCE_SHIELD_SKIN(new String[] { "giveskin PRICKLY_STANCE_SHIELD %player%" }, Material.SHIELD, "&e&lPrickly Stance Shield Skin", null, 10004),
    DEEP_DIVE_SHIELD_SKIN(new String[] { "giveskin DEEP_DIVE_SHIELD %player%" }, Material.SHIELD, "&e&lDeep Dive Shield Skin", null, 10005),
    JUICY_BERRIE_SHIELD_SKIN(new String[] { "giveskin JUICY_BERRIE_SHIELD %player%" }, Material.SHIELD, "&e&lJuicy Berrie Shield Skin", null, 10006),
    GLOWING_KRAKEN_SHIELD_SKIN(new String[] { "giveskin GLOWING_KRAKEN_SHIELD %player%" }, Material.SHIELD, "&e&lGlowing Kraken Shield Skin", null, 10007),
    PEACEFUL_FORCE_SHIELD_SKIN(new String[] { "giveskin PEACEFUL_FORCE_SHIELD %player%" }, Material.SHIELD, "&e&lPeaceful Force Shield Skin", null, 10008),

    //shears
    JUNGLE_SHEARS_SKIN(new String[] { "giveskin JUNGLE_SHEARS %player%" }, Material.SHEARS, "&e&lJungle Shears Skin", null, 11000),
    EMERALD_BLADE_SHEARS_SKIN(new String[] { "giveskin EMERALD_BLADE_SHEARS %player%" }, Material.SHEARS, "&e&lEmerald Blade Shears Skin", null, 11001),
    SILKY_BUTTER_SHEARS_SKIN(new String[] { "giveskin SILKY_BUTTER_SHEARS %player%" }, Material.SHEARS, "&e&lSilky Butter Shears Skin", null, 11002),
    HERO_STONE_SHEARS_SKIN(new String[] { "giveskin HERO_STONE_SHEARS %player%" }, Material.SHEARS, "&e&lHero Stone Shears Skin", null, 11003),
    ROYAL_SHEARS_SKIN(new String[] { "giveskin ROYAL_SHEARS %player%" }, Material.SHEARS, "&e&lRoyal Shears Skin", null, 11004),

    //fishing rod
    BROKEN_BRANCH_FISHING_ROD_SKIN(new String[] { "giveskin BROKEN_BRANCH_FISHING_ROD %player%" }, Material.FISHING_ROD, "&e&lBroken Branch Fishing Rod Skin", null, 12000),
    OLD_FAITHFUL_FISHING_ROD_SKIN(new String[] { "giveskin OLD_FAITHFUL_FISHING_ROD %player%" }, Material.FISHING_ROD, "&e&lOld Faithful Fishing Rod Skin", null, 12001),
    SUNKEN_GEM_FISHING_ROD_SKIN(new String[] { "giveskin SUNKEN_GEM_FISHING_ROD %player%" }, Material.FISHING_ROD, "&e&lSunken Gem Fishing Rod Skin", null, 12002),
    INSIGHT_FISHING_ROD_SKIN(new String[] { "giveskin INSIGHT_FISHING_ROD %player%" }, Material.FISHING_ROD, "&e&lInsight Fishing Rod Skin", null, 12003),
    WADDLES_FISHING_ROD_SKIN(new String[] { "giveskin WADDLES_FISHING_ROD %player%" }, Material.FISHING_ROD, "&e&lWaddles Fishing Rod Skin", null, 12004),
    FAITHKEEPER_ROD_SKIN(new String[] { "giveskin FAITHKEEPER_ROD %player%" }, Material.FISHING_ROD, "&e&lFaithkeeper Fishing Rod Skin", null, 12005),
    MIDNIGHT_ECHO_FISHING_ROD_SKIN(new String[] { "giveskin MIDNIGHT_ECHO_FISHING_ROD %player%" }, Material.FISHING_ROD, "&e&lMidnight Echo Fishing Rod Skin", null, 12006),

    //crossbow
    FURY_CROSSBOW_SKIN(new String[] { "giveskin FURY_CROSSBOW %player%" }, Material.CROSSBOW, "&e&lFury Crossbow Skin", null, 13000),
    RAINBOW_CROSSBOW_SKIN(new String[] { "giveskin RAINBOW_CROSSBOW %player%" }, Material.CROSSBOW, "&e&lRainbow Crossbow Skin", null, 13001),
    GALAXY_SHOT_CROSSBOW_SKIN(new String[] { "giveskin GALAXY_SHOT_CROSSBOW %player%" }, Material.CROSSBOW, "&e&lGalaxy Shot Crossbow Skin", null, 13002),
    KISS_OF_DEATH_CROSSBOW_SKIN(new String[] { "giveskin KISS_OF_DEATH_CROSSBOW %player%" }, Material.CROSSBOW, "&e&lKiss Of Death Crossbow Skin", null, 13003),
    LONG_WINTER_CROSSBOW_SKIN(new String[] { "giveskin LONG_WINTER_CROSSBOW %player%" }, Material.CROSSBOW, "&e&lLong Winter Crossbow Skin", null, 13004),
    STICKY_SITUATION_CROSSBOW_SKIN(new String[] { "giveskin STICKY_SITUATION_CROSSBOW %player%" }, Material.CROSSBOW, "&e&lSticky Situation Crossbow Skin", null, 13005),
    FERAL_SOUL_CROSSBOW_SKIN(new String[] { "giveskin FERAL_SOUL_CROSSBOW %player%" }, Material.CROSSBOW, "&e&lFeral Soul Crossbow Skin", null, 13006),
    DEMON_HUNTER_CROSSBOW_SKIN(new String[] { "giveskin DEMON_HUNTER_CROSSBOW %player%" }, Material.CROSSBOW, "&e&lDemon Hunter Crossbow Skin", null, 13007),

    ;

    @Getter private final String[] commands;
    @Getter private final Material material;
    @Getter private final String name;
    @Getter private final String skin;
    @Getter private final int modelData;


    public ItemStack getItem() {
        ItemStack item = modelData > 0 ? BukkitUtils.getCustomItem(material, name, null, modelData, true) : BukkitUtils.getItem(material, name, null, skin, true);
        ItemMeta itemMeta = item.getItemMeta();
        PersistentDataContainer dataContainer = itemMeta.getPersistentDataContainer();
        dataContainer.set(new NamespacedKey(GoldmanMysteryBox.getPlugin(), "key"), PersistentDataType.STRING, name());
        item.setItemMeta(itemMeta);
        return item;
    }

}
